services:
  postgres:
    image: postgres
    container_name: postgres-produtividade
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    hostname: ${PG_HOST}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - /var/lib/postgres/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin-produtividade
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - postgres
    volumes:
      - /var/lib/pgadmin

  server:
    container_name: server-produtividade
    restart: always
    build: .
    depends_on:
      - postgres
      - pgadmin4
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/app
    env_file:
      - .env
    command: >
      sh -c "node ace migration:run &&
             npm run dev"
